export const dummyEvents = [
  {
    name: "Lorem",
    location: "Equine Performance Innovative Center",
    locationAddress: "5590 NW Hwy 225",
    locationCity: "Ocala",
    locationState: "FL",
    locationZipcode: "34482",
    locationRollCallAndInspection: "9:00 AM",
    date: "12/14/2020",
    mainPage: true,
    calendarPage: true,
    eventsPage: true,
    pdfPresent: true,
    pdfFile: "",
    desc: "Minim qui cillum tempor ex qui esse velit.",
  },
  {
    name: "Lorem",
    location: "Equine Performance Innovative Center",
    locationAddress: "5590 NW Hwy 225",
    locationCity: "Ocala",
    locationState: "FL",
    locationZipcode: "34482",
    locationRollCallAndInspection: "9:00 AM",
    date: "12/15/2020",
    mainPage: true,
    calendarPage: true,
    eventsPage: true,
    pdfPresent: true,
    pdfFile: "",
    desc: "Minim qui cillum tempor ex qui esse velit.",
  },
  {
    name: "Lorem",
    location: "Equine Performance Innovative Center",
    locationAddress: "5590 NW Hwy 225",
    locationCity: "Ocala",
    locationState: "FL",
    locationZipcode: "34482",
    locationRollCallAndInspection: "9:00 AM",
    date: "12/21/20",
    mainPage: true,
    calendarPage: true,
    eventsPage: true,
    pdfPresent: true,
    pdfFile: "",
    desc: "Minim qui cillum tempor ex qui esse velit.",
  },
  {
    name: "Lorem",
    location: "Equine Performance Innovative Center",
    locationAddress: "5590 NW Hwy 225",
    locationCity: "Ocala",
    locationState: "FL",
    locationZipcode: "34482",
    locationRollCallAndInspection: "9:00AM",
    date: "12/22/20",
    mainPage: true,
    calendarPage: true,
    eventsPage: true,
    pdfPresent: true,
    pdfFile: "",
    desc: "Minim qui cillum tempor ex qui esse velit.",
  },
];
