export const dummyEvents = [
  {
    name: "Lorem",
    location: "Equine Performance Innovative Center",
    locationAddress: "5590 NW Hwy 225",
    locationCity: "Ocala",
    locationState: "FL",
    locationZipcode: "34482",
    locationRollCallAndInspection: "9:00 AM",
    date: "2020-12-14",
    mainPage: true,
    calendarPage: true,
    eventsPage: true,
    pdfPresent: true,
    pdfFile: "",
  },
  {
    name: "Lorem",
    location: "Equine Performance Innovative Center",
    locationAddress: "5590 NW Hwy 225",
    locationCity: "Ocala",
    locationState: "FL",
    locationZipcode: "34482",
    locationRollCallAndInspection: "9:00 AM",
    date: "2020-12-15",
    mainPage: true,
    calendarPage: true,
    eventsPage: true,
    pdfPresent: true,
    pdfFile: "",
  },
  {
    name: "Lorem",
    location: "Equine Performance Innovative Center",
    locationAddress: "5590 NW Hwy 225",
    locationCity: "Ocala",
    locationState: "FL",
    locationZipcode: "34482",
    locationRollCallAndInspection: "9:00 AM",
    date: "2020-12-21",
    mainPage: true,
    calendarPage: true,
    eventsPage: true,
    pdfPresent: true,
    pdfFile: "",
  },
  {
    name: "Lorem",
    location: "Equine Performance Innovative Center",
    locationAddress: "5590 NW Hwy 225",
    locationCity: "Ocala",
    locationState: "FL",
    locationZipcode: "34482",
    locationRollCallAndInspection: "9:00 AM",
    date: "2020-12-22",
    mainPage: true,
    calendarPage: true,
    eventsPage: true,
    pdfPresent: true,
    pdfFile: "",
  },
];
